name: Release Workflow

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build
        run: |
          # Place your build commands here
          npm run build

      - name: Exclude phpstan.neon
        run: |
          # Exclude phpstan.neon from the release
          git update-index --skip-worktree phpstan.neon

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            **Release ${{ github.ref }}**

            * Includes the following changes:
              - Any changes you want to list here

          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.ACCES_TOKEN }}

      - name: Publish Release Assets
        id: upload-release-assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/*
          asset_name: wpkenteken-v*.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.ACCES_TOKEN }}

      - name: Disable Resilience
        run: |
          echo "Setting resilience to false"
          echo "resilience: false" >> .github/workflows/release.yml
