name: Release

on:
  release:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          npm run build
      - name: Prepare release
        run: |
          echo "Excluding phpstan.neon from release"
          git update-index --skip-worktree phpstan.neon

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            **Release ${{ github.ref }}**

            * Includes the following changes:**

            {{ commit_messages }}

          draft: false
          prerelease: false

      - name: Publish release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          asset_path: dist/*
          asset_name: wpkenteken-v*.zip
          asset_content_type: application/zip

      - name: Disable resilience
        run: |
          echo "Setting resilience to false"
          echo "resilience: false" >> .github/workflows/release.yml