name: Exclude File from Release

on:
  release:
    types:
      - created

jobs:
  exclude_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Git Identity
      run: |
        git config --global user.email "sandervdwindt@gmail.com"
        git config --global user.name "sam"

    - name: Switch to the main branch
      run: |
        git checkout main

    - name: Exclude file from release
      run: |
        git rm --cached phpstan.neon
        git commit -m "Exclude phpstan.neon from release" || true
        git push origin HEAD:main
